### ISSUE TITLE
Cannot create component tags with list/set

### ISSUE THREAD

**Issue by chanpl** [ZettaIO/cachet-client#18]
Hi,

According to the documentation, component tag is a type of Set. However, it doesn't work as expected.

```
>>> cli.components.create(name="test1", status=1, tags=set(["tag1", "tag2"]))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/devel/.tox/py36/lib/python3.6/site-packages/cachetclient/v1/components.py", line 188, in create
    'tags': tags,
  File "/home/user/devel/.tox/py36/lib/python3.6/site-packages/cachetclient/base.py", line 136, in _create
    response = self._http.post(path, data=data)
  File "/home/user/devel/.tox/py36/lib/python3.6/site-packages/cachetclient/httpclient.py", line 37, in post
    return self.request('POST', path, data=data)
  File "/home/user/devel/.tox/py36/lib/python3.6/site-packages/cachetclient/httpclient.py", line 53, in request
    timeout=self.timeout,
  File "/home/user/devel/.tox/py36/lib/python3.6/site-packages/requests/sessions.py", line 516, in request
    prep = self.prepare_request(req)
  File "/home/user/devel/.tox/py36/lib/python3.6/site-packages/requests/sessions.py", line 459, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/user/devel/.tox/py36/lib/python3.6/site-packages/requests/models.py", line 317, in prepare
    self.prepare_body(data, files, json)
  File "/home/user/devel/.tox/py36/lib/python3.6/site-packages/requests/models.py", line 467, in prepare_body
    body = complexjson.dumps(json)
  File "/home/user/devel/.tox/py36/lib/python3.6/site-packages/simplejson/__init__.py", line 395, in dumps
    return _default_encoder.encode(obj)
  File "/home/user/devel/.tox/py36/lib/python3.6/site-packages/simplejson/encoder.py", line 296, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/user/devel/.tox/py36/lib/python3.6/site-packages/simplejson/encoder.py", line 378, in iterencode
    return _iterencode(o, 0)
  File "/home/user/devel/.tox/py36/lib/python3.6/site-packages/simplejson/encoder.py", line 273, in default
    o.__class__.__name__)
TypeError: Object of type set is not JSON serializable
```

```
>>> cli.components.create(name="test1", status=1, tags=["tag1", "tag2"])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/devel/.tox/py36/lib/python3.6/site-packages/cachetclient/v1/components.py", line 188, in create
    'tags': tags,
  File "/home/user/devel/.tox/py36/lib/python3.6/site-packages/cachetclient/base.py", line 136, in _create
    response = self._http.post(path, data=data)
  File "/home/user/devel/.tox/py36/lib/python3.6/site-packages/cachetclient/httpclient.py", line 37, in post
    return self.request('POST', path, data=data)
  File "/home/user/devel/.tox/py36/lib/python3.6/site-packages/cachetclient/httpclient.py", line 60, in request
    response.raise_for_status()
  File "/home/user/devel/.tox/py36/lib/python3.6/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://swarm.imagine-sw.com:8400/status/api/v1/components
>>>
```

**Comment by einarf** [comment]
This is definitely a bit confusing. During creation it should accept a list of tag names. What version of cachet are you using?

**Comment by chanpl** [comment]
Hi einarf,

I am using Cachet 2.4.

**Comment by einarf** [comment]
This was definitely a really stupid mistake. The way we expose tags are also badly designed currently. We only expose the tag slug and not the actual tag name.

I think it might be better to solve this once and for all and do a 4.0 release.

**Comment by einarf** [comment]
4.0.x is now released with improved tag support
